### ISSUE TITLE
实验疑问

### ISSUE THREAD

**Issue by macanv** [GreedyGeorge/COIN#3]
感谢开源，在实验处有些地方不是很理解。

1. ECSpell数据集下的实验结果是coin(bert)还是coin(scope) 啊？
2. 在4.3节第一段中说使用了wiki和news数据集，请问这个数据集是对bert 做pretrain任务还是和Wu的工作一样，使用混淆集构建CSC语料进行csc任务微调？
感谢。

**Comment by macanv** [comment]
还有个想请教一下，是否可以提供coin(bert) 在sighan15上detection维度上的指标？

**Comment by GreedyGeorge** [comment]
1. ECSpell的结果是COIN(BERT)
2. 和Wu的工作一样
希望对你有帮助

**Comment by macanv** [comment]
谢谢，理解了。在此表示感谢。
